//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xinchen.ExtNetBase {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xinchen.ExtNetBase.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var uploader = new plupload.Uploader({ //实例化一个plupload上传对象
        ///    browse_button: &apos;_btnSelectFile&apos;,
        ///    url: &apos;{uploadUrl}&apos;,
        ///    flash_swf_url: &apos;js/Moxie.swf&apos;,
        ///    silverlight_xap_url: &apos;js/Moxie.xap&apos;,
        ///    prevent_duplicates: true,
        ///    filters:
        ///         [ //只允许上传图片文件
        ///          { title: &apos;图片文件&apos;, extensions: &apos;jpg,gif,png&apos; }
        ///         ]
        ///});
        ///uploader.init(); //初始化
        ///uploader.bind(&apos;FilesAdded&apos;, function (uploader, files) {
        ///    for (var i = 0, len = files.length; i &lt; len; i++) {
        ///        previewImage(files[i], [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string uploader {
            get {
                return ResourceManager.GetString("uploader", resourceCulture);
            }
        }
    }
}
